export const teamLogos = {
    "Man City":     "data/logos/man-city.png",
    "Liverpool":    "data/logos/liverpool.png",
    "Arsenal":      "data/logos/arsenal.png",
    "Chelsea":      "data/logos/chelsea.png",
    "Man United":   "data/logos/man-united.png",
    "Tottenham":    "data/logos/tottenham.png",
    "Everton":      "data/logos/everton.png",
    "Leicester":    "data/logos/leicester.png",
    "West Ham":     "data/logos/west-ham.png",
    "Aston Villa":  "data/logos/aston-villa.png",
    "Newcastle":    "data/logos/newcastle.png",
    "Wolves":       "data/logos/wolves.png",
    "Brighton":     "data/logos/brighton.png",
    "Brentford":    "data/logos/brentford.png",
    "Crystal Palace": "data/logos/crystal-palace.png",
    "Fulham":       "data/logos/fulham.png",
    "Bournemouth":  "data/logos/bournemouth.png",
    "Nott'm Forest": "data/logos/forest.png",
    "Southampton":  "data/logos/southampton.png",
    "Leeds":        "data/logos/leeds.png",
    "Burnley":      "data/logos/burnley.png",
    "Watford":      "data/logos/watford.png",
    "Norwich":      "data/logos/norwich.png",
    "Sheffield United": "data/logos/sheffield-united.png",
    "Huddersfield": "data/logos/huddersfield.png",
    "Swansea":      "data/logos/swansea.png",
    "Stoke":        "data/logos/stoke.png",
    "West Brom":    "data/logos/west-brom.png",
    "Middlesbrough": "data/logos/middlesbrough.png",
    "Sunderland":   "data/logos/sunderland.png",
    "Hull":         "data/logos/hull.png",
    "Cardiff":      "data/logos/cardiff.png",
    "Ipswich":      "data/logos/ipswich.png",
    "Luton":        "data/logos/luton.png",
};

export function getTeamLogo(team) {
    return teamLogos[team] || null;
}
